In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [4]:
arr=np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [6]:
a=np.array([1,2,3,"hello"])
a

array(['1', '2', '3', 'hello'], dtype='<U21')

In [8]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])

l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [16]:
arr=np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [24]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [26]:
np.random.rand(10)

array([0.89057985, 0.9879658 , 0.84079735, 0.53727002, 0.15361885,
       0.75886011, 0.14084806, 0.51327034, 0.67832033, 0.22022021])

In [34]:
np.random.randn(10)

array([ 0.38682085,  0.80991041,  0.82852971, -0.47154632, -0.6891383 ,
        0.02987212, -0.72183809, -2.19668909, -0.00296491, -0.41342297])

In [40]:
np.random.randint(10,20,10)

array([12, 16, 18, 13, 12, 13, 14, 17, 11, 11], dtype=int32)

In [49]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.shape

(3, 3)

In [44]:
arr.size

9

In [50]:
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr.min()

np.int64(1)

In [52]:
arr.max()

np.int64(9)

In [53]:
arr.sum()

np.int64(45)

In [55]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [56]:
arr.mean()

np.float64(5.0)

In [57]:
arr.std()

np.float64(2.581988897471611)

In [58]:
arr.argmax()

np.int64(8)

In [59]:
arr.argmin()

np.int64(0)

In [61]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [67]:
arr=arr.reshape(6,5)

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])